config/routes.rb
Chapter3::Application.routes.draw do
 
 resources :users
 
 resources :articles do
    resources :comments
 end

 resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'

 
 match '/home', to: 'static_pages#home'
 match '/help', to: 'static_pages#help'
 match '/about', to: 'static_pages#about'
 match '/contact', to: 'static_pages#contact'

 match '/signup',  to: 'users#new'

 match '/signin', to: 'sessions#new'
 match '/signout', to: 'sessions#destroy', via: :delete

 match '/km',  to: 'static_pages#km'

 match '/pm',  to: 'static_pages#pm'

 match '/time',  to: 'static_pages#time'
 match '/ecommerce',  to: 'static_pages#ecommerce'
 match '/product',  to: 'static_pages#product'
 match '/mobile',  to: 'static_pages#mobile'
 match '/movie',  to: 'static_pages#movie'
 match '/logic',  to: 'static_pages#logic'
 match '/read',  to: 'static_pages#read'
 match '/life',  to: 'static_pages#life'
match '/web',  to: 'static_pages#web'

match '/java',  to: 'static_pages#java'

match '/ruby',  to: 'static_pages#ruby'
match '/data',  to: 'static_pages#data'

match '/searchresult',  to: 'static_pages#searchresult'

end

app/views/shared/_about.html.erb
<div class="row">
	

	<div class="span6">
	    <table class="table table-striped">
	   		<tr>
	   			<td>开发环境：<td>
	   			<td>Ubuntu13.04、 sqlite3<td>	
	   		</tr>
	   		<tr>
	   			<td>开发工具：<td>
	   			<td>sublime2<td>	
	   		</tr>

	   		<tr>
	   			<td>开发语言：<td>
	   			<td>ruby1.9.3、 rails3.2.13、 bootstrap<td>	
	   		</tr>

	   		<tr>
	   			<td>源码索取：<td>
	   			<td><%=link_to '联系作者',contact_path%><td>	
	   		</tr>

	    </table>

	</div>

	<div div class="span4" align="center">
		<section>
		<img src="assets/rails.png">
	    </section>

	</div>

	

</div>

app/views/shared/_article.html.erb
 <section>
 	       <%= render 'shared/success' %>	
    	   <p align="center"><strong><%=@article.title%></strong><p>
		   <p align="center"><small>标签:<%=@article.tag%> &nbsp; &nbsp; &nbsp; 新建时间:<%=@article.created_at%></small></p>
		    
		    </br>
		   <%=raw @article.content%>
			</br>	
 </section>				

app/views/shared/_contact.html.erb
<div class="row">
	
	<div class="span10">
		<strong>联系方式</strong>
	    <table class="table table-striped">
	   		<tr>	   			
	   			<td width="15%"><small>邮箱：</small></td>
	   			<td align="left"><small>zheng_jiajun@foxmail.com</small></td>
	   		</tr>
	   		<tr>
	   			<td><small>住址：</small></td>
	   			<td align="left"><small>浙江大学玉泉校区</small></td>	
	   		</tr>

	   		<tr>
	   			<td><small>家乡：</small></td>
	   			<td align="left"><small>浙江省象湖村</small></td>	
	   		</tr>
	    </table>
	</div>
</div>

<div class="row">
	<div class="span10">
		<strong>求学经历</strong>
	    <table class="table table-striped">
	   		<tr>	   			
	   			<td width="15%"><small>1996-2001</small></td>
	   			<td align="left"><small>象湖完小;01年考入五里初中，年级第一</small></td>
	   		</tr>
	   		<tr>
	   			<td><small>2001-2004：</small></td>
	   			<td align="left"><small>五里初中;04年考入衢州一中，中考成绩招贤镇第一</small></td>	
	   		</tr>
	   		<tr>
	   			<td><small>2004-2007：</small></td>
	   			<td align="left"><small>衢州一中;07年就读温州大学，机电工程学院。</small></td>	
	   		</tr>
	   		<tr>
	   			<td><small>2007-2011：</small></td>
	   			<td align="left"><small>温州大学;11年考入浙江大学,成为温州大学机电工程学院历史上第一个考入浙大的学生</small></td>	
	   		</tr>
	   		<tr class="success">
	   			<td><strong>2011-至今</strong></td>
	   			<td ><font color="red"><strong>浙江大学;研究方向:制造业信息化和知识管理</strong></font></td>	
	   		</tr>
	    </table>
	</div>

</div>

<div class="row">
	<div class="span10">
		<strong>兴趣爱好</strong>
	    <table class="table table-striped">
	   		<tr>	   			
	   			<td rowspan="3" width="15%"><strong>阅读：</strong></td>
	   			<td align="left"><small>武侠：金庸（最爱《笑傲江湖》）、古龙 、沧月、 时未寒、 凤歌 </small></td>
	   		</tr>

	   		<tr>
	   			<td align="left"><small>思维：《异类》、《引爆流行》 、《思考力决定竞争力》、《金字塔原理》 </small></td>
	   			
	   		</tr>
	   			<td align="left"><small>作者：金庸、 余华、 韩寒、 郎咸平、 大前研一 </small></td>
	   		<tr>

	   		</tr>

	   		<tr>	   			
	   			<td rowspan="2" width="10%"><strong>运动：</strong></td>
	   			<td align="left"><small>乒乓球： 擅长左手横排反手,常年混迹于学校乒乓球馆</small></td>
	   		</tr>
	   		<tr>
	   			<td align="left"><small>爬山：自从到了老和山职业技术学院，爱上爬山</small></td>
	   		</tr>


	   	
	    </table>
	</div>

</div>

app/views/shared/_ecommerces.html.erb
<ol>
	<%@ecommerces.each do |ecommerce|%>
		<li><%=link_to ecommerce.title,article_path(ecommerce)%>
		</li>
	<%end%>
</ol>

app/views/shared/_javas.html.erb
<ol>
<%@javas.each do |java|%>
	<li><%=link_to java.title,article_path(java)%></br>
		<%=java.content%></li>
<%end%>
</ol>

app/views/shared/_jss.html.erb
<ul>
<%@jss.each do |js|%>
	<li><%=link_to js.title,article_path(js)%></br>
		<%=js.content%></li>
<%end%>
</ul>

app/views/shared/_kms.html.erb
<ol>
<%@kms.each do |km|%>
	<li><%=link_to km.title,article_path(km)%></li>
<%end%>
</ol>

app/views/shared/_pms.html.erb
<ol>
<%@pms.each do |pm|%>
	<li><%=link_to pm.title,article_path(pm)%>
	</li>
<%end%>
</ol>

app/views/shared/_rails.html.erb
<ol>
<%@rails.each do |rail|%>
	<li><%=link_to rail.title,article_path(rail)%></li>
<%end%>
</ol>

app/views/shared/_reads.html.erb
<ol>
	<%@reads.each do |read|%>
		<li><%=link_to read.title,article_path(read)%>
		</li>
	<%end%>
</ol>

app/views/shared/_searchresult.html.erb
 <section>
 	  <% if @articles_results.empty? %>
      <p align="center"><font color="337FE5">对不起，没有搜索到您要文章！</font></p>
      <% else %>
	    
	    	<p align="center"><font color="337FE5">找到<%=@articles_results.count%>篇文章！</font></p>
		    <%@articles_results.each do |result|%>
				<p><strong><font><%=link_to result.title,article_path(result)%></strong></font></p></br>
				<%=raw result.content%>
			<hr>				
		    <%end%>	   
	    
	  <%end%>
    
<section>

app/views/shared/_times.html.erb
<ol>
	<%@times.each do |time|%>
		<li><%=link_to time.title,article_path(time)%>
		</li>
	<%end%>
</ol>
 

app/views/shared/_tips.html.erb
<section>   
	  <ul>    
	    <hr>
		<li><%=link_to '产品经理',pm_path%>(<%=@pms.count%>)</li>
		<li><%=link_to '知识管理',km_path%>(<%=@kms.count%>)</li>
		<li><%=link_to '时间管理',time_path%>(<%=@times.count%>)</li>
		<hr>

		<li><%=link_to '互联网产品',product_path%>(<%=@products.count%>)</li>
		<li><%=link_to '电子商务',ecommerce_path%>(<%=@ecommerces.count%>)</li>
		<li><%=link_to '移动互联网',mobile_path%>(<%=@mobiles.count%>)</li>


		<hr>
		<li><%=link_to '电影人生',movie_path%>(<%=@movies.count%>)</li>
		<li><%=link_to '思维逻辑',logic_path%>(<%=@logics.count%>)</li>
		<li><%=link_to '阅读空间',read_path%>(<%=@reads.count%>)</li>
		<li><%=link_to '生活感悟',life_path%>(<%=@lifes.count%>)</li>
		<hr>

		<li><%=link_to 'web开发',web_path%>(<%=@webs.count%>)</li>
		<li><%=link_to 'java学习',java_path%>(<%=@javas.count%>)</li>
		<li><%=link_to 'ruby学习',ruby_path%>(<%=@rubys.count%>)</li>
		<li><%=link_to '数据结构',data_path%>(<%=@datas.count%>)</li>









	  </ul>
</section>

app/views/shared/_webs.html.erb
<ol>
<%@webs.each do |web|%>
	<li><%=link_to web.title,article_path(web)%></br>
		<%=raw web.content%></li>
<%end%>
</ol>